name: nestjs-boilerplate
services:
  app:
    build:
      context: ../..
      dockerfile: infra/docker/dev.Dockerfile
    container_name: api
    ports:
      - 3002:3002
    volumes:
      - ../../src/:/app/src/
      - ../../.env:/app/.env
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3002/api/v1/internal/health']
      interval: 60s
      timeout: 2s
      retries: 3

  postgres:
    container_name: pg
    image: postgres:12.4-alpine
    env_file: ../../.env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 3s
      timeout: 2s
      retries: 5

volumes:
  db:
